import { useParams, Link } from 'react-router-dom';
import { useEffect } from 'react';


export default function ItemDetail() {
    const productos = [
        { id: 1, section: "Historia", title: "Operación Barbarosa", Autor: "Christian Hartman", price: 100, pictureUrl: "https://cdn.zendalibros.com/wp-content/uploads/2018/10/portada_operacion_barbarroja-e1538551211392.jpg", descripcion: "OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana. A primera hora de la mañana del 22 de junio de 1941, las tropas alemanas invadieron la Unión Soviética. Acababa de comenzar la Operación Barbarroja y durante los cuatro años siguientes, el país se sumergiría en una época de violencia. Christian Hartmann, uno de los más reputados y aclamados historiadores militares alemanes, describe el curso de la guerra de conquista. OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana. A primera hora de la mañana del 22 de junio de 1941, las tropas alemanas invadieron la Unión Soviética. Acababa de comenzar la Operación Barbarroja y durante los cuatro años siguientes, el país se sumergiría en una época de violencia. Christian Hartmann, uno de los más reputados y aclamados historiadores militares alemanes, describe el curso de la guerra de conquista y aniquilación en el este sobre la base de las más recientes investigaciones, lo incorpora al relato dramático del conflicto y describe sus efectos, que aún pueden apreciarse hoy en día. OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana." },
        { id: 2, section: "Historia", title: "Arquitectura y construcción incas en Ollantaytambo", Autor: "Jean-Pierre Protzen", price: 110, pictureUrl: "https://imgv2-1-f.scribdassets.com/img/word_document/428426028/original/7baa722d8d/1654043302?v=1", descripcion: "Estudio que describe la relación del hombre con su ambiente, la comprensión y respeto de la geomorfología, hidrología y topografía por parte de los incas, su consideración por el medio y su sensibilidad por las condiciones microclimáticas específicas. Ollantaytambo, una propiedad real del Inca Pachakuti (c. 1438-1490), es un complejo menos conocido que Machu Picchu, otra propiedad real. Sin embargo, no es un ejemplo menos impresionante y significativo de las habilidades arquitectónicas y de planificación de los incas. En Ollantaytambo se puede encontrar el espectro completo del programa constructivo de los incas. Existen evidencias de trabajos de infraestructura como canteras, caminos y puentes, fortificaciones, ríos canalizados, amplias terrazas agrícolas y sistemas de irrigación, ­muchos de los cuales continúan en uso, y mucha arquitectura en pie en forma de estructuras de almacenamiento, un asentamiento completo con edificios incas originales aún habitados, templos, fuentes, piedras grabadas y otros lugares de culto." },
        { id: 3, section: "Historia", title: "Estructuras políticas y económicas de la costa central del Perú precolombino. Obras completas XI", Autor: "María Rostworowski", price: 130, pictureUrl: "https://simehbucket.s3.amazonaws.com/images/5a2d2f9c29b2605bc4176f8068b09afc-large.jpg", descripcion: "El estudio del pasado prehispánico de la costa central peruana, en particular de las sociedades desarrolladas en el valle de Lurín, ha sido el foco de una serie de controversias por parte de los especialistas en esta región. Tales controversias se centran sobre todo en el papel jugado por el santuario de Pachacamac en la organización social del valle bajo y medio de Lurín." },
        { id: 4, section: "Infantiles", title: "Las aventuras de Pinocho", Autor: "Carlo Collodi", price: 40, pictureUrl: "https://www.elejandria.com/covers/Las_aventuras_de_Pinocho-Carlo_Collodi-md.png", descripcion: "Este libro electrónico está libre de restricciones de derechos de autor en España. Si no se encuentra en España, debe consultar las leyes locales para verificar que el contenido de este libro electrónico esté libre de restricciones de derechos de autor en el país en el que se encuentra antes de descargar este libro electrónico. Si está libre de restricciones, puedes descargar gratis Las aventuras de Pinocho." },
        { id: 5, section: "Infantiles", title: "El cerdito de Navidad", Autor: "J.K. Rowling", price: 56, pictureUrl: "https://images-na.ssl-images-amazon.com/images/I/51S807JfF8S._SX323_BO1,204,203,200_.jpg", descripcion: "Dito es el juguete preferido de Jack. Siempre ha estado a su lado, en los buenos y malos momentos. Hasta que el día de Nochebuena sucede algo terrible: Dito se pierde. Pero es una noche especial, una noche para los milagros y los casos perdidos, una noche en la que los objetos, incluidos los juguetes, pueden cobrar vida. Y el juguete que le han regalado a Jack, el nuevo cerdito de Navidad (el frustrante sustituto de Dito), tramará un plan muy arriesgado. Juntos se embarcarán en un viaje mágico para intentar recuperar y salvar al que hasta ahora ha sido el mejor amigo de Jack." },
        { id: 6, section: "Infantiles", title: "Paula y La Luna", Autor: "Alberto Sánchez Argüello", price: 75, pictureUrl: "https://images-na.ssl-images-amazon.com/images/I/51a-CCDQoaL._SX333_BO1,204,203,200_.jpg", descripcion: "Paula siempre ha querido ir a la Luna. Ha hecho toda clase de intentos para llegar hasta allí, desde tratar de alcanzarla subida a hombros de papá hasta construir su propio cohete y hacerlo volar con burbujas de jabón y cometas. Paula sigue soñando con volar a la Luna. Cada noche piensa que cuando sea mayor aprenderá a vencer la ley de la gravedad." },
        { id: 7, section: "Novelas", title: "Orgullo y Prejuicio", Autor: "Jane Austen", price: 60, pictureUrl: "https://cdn.culturagenial.com/es/imagenes/orgullo-prejuicio-portada-cke.jpg", descripcion: "Maravillosa edición ilustrada de Alfaguara Clásicos de Orgullo y prejuicio de Jane Austen, una de las historias de amor más cautivadoras de la historia y un clásico de la literatura universal. La familia Bennet tiene cinco hijas, así que la llegada al vecindario de Mr. Bingley, un joven rico y soltero, es todo un acontecimiento. Mientras Mr. Bingley se embelesa con Jane, la mayor de las hermanas, el altivo Mr. Darcy y la alegre Elizabeth pronto se enzarzan en una serie de desdenes y malentendidos que deberán reconocer y afrontar para poder alcanzar la felicidad. Clásicos inolvidables para disfrutar, compartir y dejar volar la imaginación. En los blogs...«¡Qué libros señores! ¡Cómo lo disfruté! Un clásico que no pasa de moda, un clásico que hay que leer seas de dónde seas, tengas la edad que tengas, estés en el año que estés.»Javier Ruescas" },
        { id: 8, section: "Novelas", title: "El cuaderno de Noah", Autor: "Nicholas Sparks", price: 35, pictureUrl: "https://images-na.ssl-images-amazon.com/images/I/514F0inZVyL._SX328_BO1,204,203,200_.jpg", descripcion: "Un hombre tiene un cuaderno viejo, traído y llevado mil veces, en su regazo. Una mujer a su lado escucha lo que él le lee cada mañana, aunque no acaba de entender. Muchos años antes, Noah Calhoun, vuelve a casa, a Carolina del Norte, después de la Segunda Guerra Mundial. Noah, de 31 años, intenta que la plantación de la que procede vuelva a su antigua gloria, pero las imágenes de la preciosa joven que conoció catorce años antes ?una mujer a la que amó como a ninguna otra? no paran de perseguirle. " },
        { id: 9, section: "Poesía", title: "Mi Primer Libro de Poesía", Autor: "José Luis Ferris", price: 30, pictureUrl: "https://www.anayainfantilyjuvenil.com/images/libros/grande/9788469833384-mi-primer-libro-de-poesia-mi-primer-libro.jpg", descripcion: "Un libro que iniciará en la literatura a los niños de un modo natural, ya que se han seleccionado poemas de entre los mejores escritores de la literatura española e hispanoamericana buscando los textos más alegres, musicales y fáciles de recitar y aprender y además van acompañados de ilustraciones a todo color." },
        { id: 10, section: "Novelas", title: "Drama Queen", Autor: "Martínez Roca", price: 50, pictureUrl: "https://libreria.tirant.com/high/9788427049895.jpg", descripcion: "Una novela ilustrada basada en anécdotas, humor, amor, sexo, comedias y sobre todo dramas. ¡Mira que eres dramas! Cansada de que me digan siempre que querer es poder, que lo importante es que me ría de mí misma y que todo es más sencillo de lo que me imagino, me planto ante la vida y pienso: ¿solo yo tengo problemas? En un mundo de influencers de pacotilla y de princesas yo elegí ser una persona que se come el mundo antes de que el mundo me coma a mí, aunque a veces tenga náuseas. Pero ¡cuidado! porque, sí, hablo de cosas de chicas y de chicos, de situaciones muy reales, de momentos alegres y de llanto, pero os lo digo alto y claro: todos y todas llevamos una Drama Queen dentro, solo hay que dejarla salir? Cuando una dramas escribe un diario, el resultado solo puede ser un relato muy gamberro y con mucho humor" },
        { id: 11, section: "Ficción", title: "La Ciencia de la Ciencia Ficción", Autor: "Manuel Moreno Lupiañez", price: 60, pictureUrl: "https://m.media-amazon.com/images/I/51ingKw+goL.jpg", descripcion: "En un famoso episodio de la no menos célebre Star Trek asistimos a una inusual partida de póker entre el androide Data y los hologramas de Albert Einstein, Isaac Newton y Stephen Hawking, el único que, por razones obvias, pudo interpretarse a sí mismo. Como en el capítulo de la serie, en este libro también comparten protagonismo ilustres científicos junto con personajes tan peculiares como Darth Vader, E.T., Spiderman o Godzilla. A lo largo de sus páginas nos planteamos si son posibles las acrobáticas piruetas del Halcón Milenario, las carreras supersónicas de Flash Gordon o los fenómenos temporales que se producen en Miller, el planeta que aparece en el film Interstellar. La ciencia ficción, además de ser un apasionante entretenimiento, es también una manera idónea de aprender las leyes de la ciencia... aunque solo sea por la cantidad de veces que no las respetan los guionistas de Hollywood." },
        { id: 12, section: "Ficción", title: "El despertar del Leviatán", Autor: "James S. A. Corey ", price: 84, pictureUrl: "https://images-na.ssl-images-amazon.com/images/I/51CYoSkO+zL._SX320_BO1,204,203,200_.jpg", descripcion: "La humanidad ha colonizado el Sistema Solar: Marte, la Luna, el cinturón de asteroides y más allá, pero las estrellas aún están fuera de nuestro alcance. Jim Holden es segundo de a bordo de un transportador de hielo que realiza misiones entre los anillos de Saturno y las estaciones mineras del Cinturón. Cuando su tripulación y él se topan con la Scopuli, una nave abandonada, descubren un secreto que desearían no haber encontrado. Un secreto por el que alguien sería capaz de matar, matar a una escala que Jim y su tripulación no imaginan. La guerra en el Sistema Solar está a punto de comenzar, a menos que sean capaces de descubrir quién abandonó la nave y por qué." },
        { id: 13, section: "Tecnología", title: "Tecnología. Juegos, Actividades y Temas Curiosos Para el Aprendizaje Tecnológico", Autor: "Belén Jacoba Martín Armand", price: 80, pictureUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788466219754_mnvd2jtltmkbv6oe.jpg", descripcion: "Stem Es un Divertido Método que Combina Aprendizaje y Juego Desde una Aplicación Práctica Basada en el Entretenimiento, Cuyo Fin Es Encontrar la Resolución a Distintos Retos Dentro de Estas Cuatro Áreas. La Tecnología Es la Ciencia Encargada de Crear Herramientas como Estas, que Hacen Nuestra Vida Más Fácil. Enfréntate a Ella Desde la Pregunta y Resuelve Tú Mismo las Actividades que Te Proponemos en Cada Tema. ¡Podrás Comprobar el Resultado al Final del Libro!" },
        { id: 14, section: "Psicología", title: "Psicología Para Principiantes", Autor: "Justin Santiago", price: 105, pictureUrl: "https://m.media-amazon.com/images/I/51vU9ppKChL.jpg", descripcion: "¿Siempre te has preguntado cómo funciona la psique humana? ¿Conoces las trampas psicológicas de las que a menudo eres víctima inconscientemente? «Los mecanismos psicológicos representan un tema que se ha investigado durante mucho tiempo. Estos mecanismos nos controlan a diario y también controlan nuestro comportamiento. Por esa razón, es aún más importante tomar conciencia de ello para poder avanzar y, además, recuperar finalmente el control del mundo de los pensamientos y sentimientos y, por tanto, de nuestra propia conducta. Para ello, necesitas una base estable sobre la que te puedas desarrollar y es por eso que la vamos a tratar en primer lugar. Aunque nos llevará algo de tiempo y requerirá energía, notarás rápidamente que valdrá la pena. A pesar de la introducción teórica al tema, esta guía está orientada en gran medida a la práctica, de forma que puedes considerarla básicamente como un entrenamiento físico. ¿De qué sirve leer la teoría de un libro por enésima vez si aún no has cogido una pesa? Exacto: ¡de nada! Por eso es muy importante que siempre realices prácticas mientras leas este libro»" },
        { id: 15, section: "Psicología", title: "La psicología que nos ayuda a vivir. ", Autor: "María Jesús Álava Reyes", price: 125, pictureUrl: "https://www.esferalibros.com/wp-content/uploads/2021/04/principal-portada-la-psicologia-que-nos-ayuda-a-vivir-es-1.jpg", descripcion: "La psicología que nos ayuda a vivir es la obra definitiva para aprender a resolver los conflictos y las dificultades que nos acechan en ese difícil día a día en que se ha convertido la realidad actual. María Jesús Álava, autora del libro La inutilidad del sufrimiento -del que se han vendido 100.000 ejemplares-, ha afrontado el reto de dirigir esta enciclopedia imprescindible que orienta a los lectores, entre otros temas, acerca de: Problemas en la relación de pareja, Niños hiperactivos, Psicología del envejecimiento, Duelos, Depresión y más" },
    ]
    const { id } = useParams()
    const dato = productos[id - 1]
    console.log(productos)
    return (
        <>
            <div className='card_detail'>
                <div>
                    <img className='imagen2' src={dato.pictureUrl} />
                </div>
                <div className=' card-detail2'>
                    <p className='text-card'>Título: <b>{dato.title}</b></p>
                    <p className='text-card'>Autor: <b>{dato.Autor}</b></p>
                    <p className='text-card'>Sección: <b>{dato.section}</b></p>
                    <p className='text-card'>Precio:   <b>S/{dato.price}</b></p>
                    <p className='text-card2'>Resumen: {dato.descripcion}</p>
                </div>
            </div>
            <Link to="/productos" className='regresar detalles'>Regresar</Link>
        </>
    )
}
