import React from 'react'
import ItemCount from './ItemCount'
import ItemList from './ItemList'
import { useState, useEffect } from 'react'

export default function ItemListContainer({ greeting }) {

  const [resultado, setResultado] = useState([])
  useEffect(() => {
    const items = new Promise((res, rej) => {
      setTimeout(() => {
        res([
          { id: 1, title: "Historia", price: 100, pictureUrl: "https://cdn.zendalibros.com/wp-content/uploads/2018/10/portada_operacion_barbarroja-e1538551211392.jpg", descripcion: "OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana. A primera hora de la mañana del 22 de junio de 1941, las tropas alemanas invadieron la Unión Soviética. Acababa de comenzar la Operación Barbarroja y durante los cuatro años siguientes, el país se sumergiría en una época de violencia. Christian Hartmann, uno de los más reputados y aclamados historiadores militares alemanes, describe el curso de la guerra de conquista ... Ver más Ocultar OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana. A primera hora de la mañana del 22 de junio de 1941, las tropas alemanas invadieron la Unión Soviética. Acababa de comenzar la Operación Barbarroja y durante los cuatro años siguientes, el país se sumergiría en una época de violencia. Christian Hartmann, uno de los más reputados y aclamados historiadores militares alemanes, describe el curso de la guerra de conquista y aniquilación en el este sobre la base de las más recientes investigaciones, lo incorpora al relato dramático del conflicto y describe sus efectos, que aún pueden apreciarse hoy en día. OPERACIÓN BARBAROJA Una excelente y breve introducción sobre la guerra alemana." },
          { id: 2, title: "Infantiles", price: 40, pictureUrl: "https://www.elejandria.com/covers/Las_aventuras_de_Pinocho-Carlo_Collodi-md.png", descripcion: "Este libro electrónico está libre de restricciones de derechos de autor en España. Si no se encuentra en España, debe consultar las leyes locales para verificar que el contenido de este libro electrónico esté libre de restricciones de derechos de autor en el país en el que se encuentra antes de descargar este libro electrónico. Si está libre de restricciones, puedes descargar gratis Las aventuras de Pinocho." },
          { id: 3, title: "Novelas", price: 60, pictureUrl: "https://cdn.culturagenial.com/es/imagenes/orgullo-prejuicio-portada-cke.jpg", descripcion: "Maravillosa edición ilustrada de Alfaguara Clásicos de Orgullo y prejuicio de Jane Austen, una de las historias de amor más cautivadoras de la historia y un clásico de la literatura universal. La familia Bennet tiene cinco hijas, así que la llegada al vecindario de Mr. Bingley, un joven rico y soltero, es todo un acontecimiento. Mientras Mr. Bingley se embelesa con Jane, la mayor de las hermanas, el altivo Mr. Darcy y la alegre Elizabeth pronto se enzarzan en una serie de desdenes y malentendidos que deberán reconocer y afrontar para poder alcanzar la felicidad. Clásicos inolvidables para disfrutar, compartir y dejar volar la imaginación. En los blogs...«¡Qué libros señores! ¡Cómo lo disfruté! Un clásico que no pasa de moda, un clásico que hay que leer seas de dónde seas, tengas la edad que tengas, estés en el año que estés.»Javier Ruescas" },
          { id: 4, title: "Poesía", price: 30, pictureUrl: "https://www.anayainfantilyjuvenil.com/images/libros/grande/9788469833384-mi-primer-libro-de-poesia-mi-primer-libro.jpg", descripcion: "Un libro que iniciará en la literatura a los niños de un modo natural, ya que se han seleccionado poemas de entre los mejores escritores de la literatura española e hispanoamericana buscando los textos más alegres, musicales y fáciles de recitar y aprender y además van acompañados de ilustraciones a todo color." },
          { id: 5, title: "Drama", price: 50, pictureUrl: "https://libreria.tirant.com/high/9788427049895.jpg", descripcion: "Una novela ilustrada basada en anécdotas, humor, amor, sexo, comedias y sobre todo dramas. ¡Mira que eres dramas! Cansada de que me digan siempre que querer es poder, que lo importante es que me ría de mí misma y que todo es más sencillo de lo que me imagino, me planto ante la vida y pienso: ¿solo yo tengo problemas? En un mundo de influencers de pacotilla y de princesas yo elegí ser una persona que se come el mundo antes de que el mundo me coma a mí, aunque a veces tenga náuseas. Pero ¡cuidado! porque, sí, hablo de cosas de chicas y de chicos, de situaciones muy reales, de momentos alegres y de llanto, pero os lo digo alto y claro: todos y todas llevamos una Drama Queen dentro, solo hay que dejarla salir? Cuando una dramas escribe un diario, el resultado solo puede ser un relato muy gamberro y con mucho humor" },
          { id: 6, title: "Ficción", price: 60, pictureUrl: "https://m.media-amazon.com/images/I/51ingKw+goL.jpg", descripcion: "En un famoso episodio de la no menos célebre Star Trek asistimos a una inusual partida de póker entre el androide Data y los hologramas de Albert Einstein, Isaac Newton y Stephen Hawking, el único que, por razones obvias, pudo interpretarse a sí mismo. Como en el capítulo de la serie, en este libro también comparten protagonismo ilustres científicos junto con personajes tan peculiares como Darth Vader, E.T., Spiderman o Godzilla. A lo largo de sus páginas nos planteamos si son posibles las acrobáticas piruetas del Halcón Milenario, las carreras supersónicas de Flash Gordon o los fenómenos temporales que se producen en Miller, el planeta que aparece en el film Interstellar. La ciencia ficción, además de ser un apasionante entretenimiento, es también una manera idónea de aprender las leyes de la ciencia... aunque solo sea por la cantidad de veces que no las respetan los guionistas de Hollywood." },
          { id: 7, title: "Tecnología", price: 80, pictureUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788466219754_mnvd2jtltmkbv6oe.jpg", descripcion: "Stem Es un Divertido Método que Combina Aprendizaje y Juego Desde una Aplicación Práctica Basada en el Entretenimiento, Cuyo Fin Es Encontrar la Resolución a Distintos Retos Dentro de Estas Cuatro Áreas. La Tecnología Es la Ciencia Encargada de Crear Herramientas como Estas, que Hacen Nuestra Vida Más Fácil. Enfréntate a Ella Desde la Pregunta y Resuelve Tú Mismo las Actividades que Te Proponemos en Cada Tema. ¡Podrás Comprobar el Resultado al Final del Libro!" },
          { id: 8, title: "Psicología", price: 105, pictureUrl: "https://m.media-amazon.com/images/I/51vU9ppKChL.jpg", descripcion: "¿Siempre te has preguntado cómo funciona la psique humana? ¿Conoces las trampas psicológicas de las que a menudo eres víctima inconscientemente? «Los mecanismos psicológicos representan un tema que se ha investigado durante mucho tiempo. Estos mecanismos nos controlan a diario y también controlan nuestro comportamiento. Por esa razón, es aún más importante tomar conciencia de ello para poder avanzar y, además, recuperar finalmente el control del mundo de los pensamientos y sentimientos y, por tanto, de nuestra propia conducta. Para ello, necesitas una base estable sobre la que te puedas desarrollar y es por eso que la vamos a tratar en primer lugar. Aunque nos llevará algo de tiempo y requerirá energía, notarás rápidamente que valdrá la pena. A pesar de la introducción teórica al tema, esta guía está orientada en gran medida a la práctica, de forma que puedes considerarla básicamente como un entrenamiento físico. ¿De qué sirve leer la teoría de un libro por enésima vez si aún no has cogido una pesa? Exacto: ¡de nada! Por eso es muy importante que siempre realices prácticas mientras leas este libro»" },
        ])
        // rej(console.log("Salio mal"))
      }, 2000);
    })
    items.then((result) => { setResultado(result) })
      .catch((error) => { console.log("salio mal", error) })
  }, [])

  const stockItem = 20
  return (
    <>
      <p>
        Esto es un {greeting}
      </p>
      <ItemCount stock={stockItem} initial={1} />
      <ItemList result={resultado} />
    </>
  )
}
